# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

#gems: [jekyll-paginate-v2]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "playlist"
      permalink: /:categories/:year/:month/:day/:title/

  - scope:
      path: "gene/_posts"
    values:
      author: "gene"
  
  - scope:
      path: "harahguast/_posts"
    values:
      author: "harahguast"

  - scope:
      path: "gene"
    values:
      author: "gene"
      layout: "posts_index"
      permalink: "/gene/"
      
  - scope:
      path: "harahguast"
    values:
      author: "harahguast"
      layout: "posts_index"
      permalink: "/harahguast/"


  - scope:
      path: "assets/img"
    values:
      image: true

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

name: "4:20"
